---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment      
  labels:
    name: worker-deployment 
    app: demo-app
spec:
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-app
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
  replicas: 1  
  selector:
    matchLabels:
      name: worker-pod 
      app: demo-app
