apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels: 
    name: result-deployment
spec:
  template:
    metadata:
      name: result-pod
      labels: 
        name: result-pod
    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result 
          ports:
            - containerPort: 80
  selector: 
    matchLabels:
      name: result-pod 
  replicas: 3
