name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:19-alpine3.16
      #options: --cpus 1 
    steps:
      - name: Log Node version
        run: |
          node -v 
          cat /etc/os-release