name: Container
on: push

jobs:
  docker-step:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16
    steps:
      - name: log node version
        run: node -v 
      - name: Step with docker 
        uses: docker://node:19.4-alpine3.17
        with:
          entrypoint: /bin/echo
          args: 'Hello World'
      - name: log node version
        uses: docker://node:19.4-alpine3.17
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - name: Run a Script
        uses: docker://node:19.4-alpine3.17
        with:
          entrypoint: ./script.sh
          args: "Some string"