name: "Shell Commands"

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Welcome to GitHub Actions Learning"
      - name: multiline scripts
        run: |
          node -v
          npm -v
      - name : python command 
        run: |
          import platform
          print(platform.processor())

